/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Kyber768Ref */

#ifndef _Included_Kyber768Ref
#define _Included_Kyber768Ref
#ifdef __cplusplus
extern "C" {
#endif
#undef Kyber768Ref_CRYPTO_PUBLICKEYBYTES
#define Kyber768Ref_CRYPTO_PUBLICKEYBYTES 1184L
#undef Kyber768Ref_CRYPTO_SECRETKEYBYTES
#define Kyber768Ref_CRYPTO_SECRETKEYBYTES 2400L
#undef Kyber768Ref_CRYPTO_CIPHERTEXTBYTES
#define Kyber768Ref_CRYPTO_CIPHERTEXTBYTES 1088L
#undef Kyber768Ref_CRYPTO_BYTES
#define Kyber768Ref_CRYPTO_BYTES 32L
/*
 * Class:     Kyber768Ref
 * Method:    generateKeypair
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_Kyber768Ref_generateKeypair
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     Kyber768Ref
 * Method:    encrypt
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_Kyber768Ref_encrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     Kyber768Ref
 * Method:    decrypt
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_Kyber768Ref_decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
