/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OffPay */

#ifndef _Included_OffPay
#define _Included_OffPay
#ifdef __cplusplus
extern "C" {
#endif
#undef OffPay_CRYPTO_PUBLICKEYBYTES
#define OffPay_CRYPTO_PUBLICKEYBYTES 1184L
#undef OffPay_CRYPTO_SECRETKEYBYTES
#define OffPay_CRYPTO_SECRETKEYBYTES 2400L
#undef OffPay_CRYPTO_CIPHERTEXTBYTES
#define OffPay_CRYPTO_CIPHERTEXTBYTES 1088L
#undef OffPay_CRYPTO_BYTES
#define OffPay_CRYPTO_BYTES 32L
/*
 * Class:     OffPay
 * Method:    generateKeypair
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_OffPay_generateKeypair
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     OffPay
 * Method:    encrypt
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_OffPay_encrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     OffPay
 * Method:    decrypt
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_OffPay_decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
