/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FalconTransactionSimulator */

#ifndef _Included_FalconTransactionSimulator
#define _Included_FalconTransactionSimulator
#ifdef __cplusplus
extern "C" {
#endif
#undef FalconTransactionSimulator_PQCLEAN_FALCON512_CLEAN_CRYPTO_SECRETKEYBYTES
#define FalconTransactionSimulator_PQCLEAN_FALCON512_CLEAN_CRYPTO_SECRETKEYBYTES 1281L
#undef FalconTransactionSimulator_PQCLEAN_FALCON512_CLEAN_CRYPTO_PUBLICKEYBYTES
#define FalconTransactionSimulator_PQCLEAN_FALCON512_CLEAN_CRYPTO_PUBLICKEYBYTES 897L
#undef FalconTransactionSimulator_PQCLEAN_FALCON512_CLEAN_CRYPTO_BYTES
#define FalconTransactionSimulator_PQCLEAN_FALCON512_CLEAN_CRYPTO_BYTES 752L
/*
 * Class:     FalconTransactionSimulator
 * Method:    generateKeyPair
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_FalconTransactionSimulator_generateKeyPair
  (JNIEnv *, jobject);

/*
 * Class:     FalconTransactionSimulator
 * Method:    signMessage
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_FalconTransactionSimulator_signMessage
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     FalconTransactionSimulator
 * Method:    verifySignature
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_FalconTransactionSimulator_verifySignature
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
