/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FalconSign */

#ifndef _Included_FalconSign
#define _Included_FalconSign
#ifdef __cplusplus
extern "C" {
#endif
#undef FalconSign_PQCLEAN_FALCON512_CLEAN_CRYPTO_SECRETKEYBYTES
#define FalconSign_PQCLEAN_FALCON512_CLEAN_CRYPTO_SECRETKEYBYTES 1281L
#undef FalconSign_PQCLEAN_FALCON512_CLEAN_CRYPTO_PUBLICKEYBYTES
#define FalconSign_PQCLEAN_FALCON512_CLEAN_CRYPTO_PUBLICKEYBYTES 897L
#undef FalconSign_PQCLEAN_FALCON512_CLEAN_CRYPTO_BYTES
#define FalconSign_PQCLEAN_FALCON512_CLEAN_CRYPTO_BYTES 752L
/*
 * Class:     FalconSign
 * Method:    generateKeyPair
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_FalconSign_generateKeyPair
  (JNIEnv *, jobject);

/*
 * Class:     FalconSign
 * Method:    signMessage
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_FalconSign_signMessage
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     FalconSign
 * Method:    verifySignature
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_FalconSign_verifySignature
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
